### ISSUE TITLE
Node package

### ISSUE THREAD

**Issue by slhck** [paulhiggs/codec-string#2]
Would you be interested in turning this into a proper Node.js package, possibly even with TypeScript support? This would make it easier to integrate the code into other codebases. For instance, instead of manually copy-pasting the source code files, one could do:

```
npm install codec-string
```

Then:

```
import { decode } from 'codec-string';

decode("…");
```

The source code and files would mostly stay as they are; they'd just be packaged quite differently. I can provide a (somewhat large) PR for that, but it'd also be a bit of a maintenance burden for you in the long term.
I could also provide my own NPM package based on your code if that's easier for you.

**Comment by paulhiggs** [comment]
I certainly agree with making this capability available as a node.js module, but have a couple of considerations

1. It would be good to ensure that 'browser use' is not inhibited. Even now, one can clone this repo and use any browser as their local application framework.
2. A module should be able to produce both HTML formatted and object based results for example `decode("...")` produces an  object while `decode("...").text()` and `decode("...").html()` produce textual and HTML marked up formats.

Some further elaboration of the 'maintenance burden' would be nice. Ideally any new decoder should be straightforward in its inclusion into a node module, although I understand that publishing on npm will require some additional documentation and effort.

**Comment by slhck** [comment]
Great, thanks for the feedback!

Regarding browser use: no problem. It would be preferable to provide a CommonJS module (for Node.js), an ES module (for “modern” tools), and a UMD module, the latter of which can directly be imported in browsers. The NPM build script would produce a `codec-string.min.js` file (or similar) which could directly be used in a `<script>` tag for import.

As for maintenance: I didn't mean to imply that adding a new decoder would become harder; that should be the same effort. Maybe I'd add a test suite to cover the currently implemented codecs. It's the publishing part that takes a bit more effort, although I think the maintenance over the lifetime of the package should be minimal, seeing that it does not have any runtime dependencies (which are often the source of breakage or security issues).

I'll provide a PR once I have a first draft ready.

**Comment by slhck** [comment]
As for the HTML and textual output, I have to check the code base in detail. It appears like we'd need to separate the concerns a little bit.

Currently, formatting is mixed in with the information, and there is no dedicated error handling. This would make it hard to use the libraries within another library.

For programmatic use, it would be preferable to be able to extract raw, unformatted string representations, and handle errors through `try/catch`. For HTML use, a dedicated formatter function could be provided. Perhaps the extracted codec information will be stored in an intermediate, internal format, from which both raw and formatted strings could be extracted. Errors would simply be thrown and left for the user (or HTML formatting function) to catch.

**Comment by paulhiggs** [comment]
What type of 'output' do you expect that a node.js application will need? Knowing that will help with improving the function calls to return something that is applicable (rather then just an HTML markup that is done today - that is what I needed at the time)

I will think some more about having each decoder return a class that can be further processed by the caller (or use some basic processing from the library). For example, the return could be
````
{name, overall_error, 
[{line, error [OK, WARNING, ERROR]}, 
 { },  ... ]}
````

if `overall_error==null` then you will likely find some decoded lines.

**Comment by slhck** [comment]
Thinking about it more, some kind of structured output would be ideal for later programmatic usage. I realize though this is not what you intended this code to do, and that this might add some extra work.

Here's a [dummy example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QCIQQewBMJCBJEGfZAbwChlkDiEAuZDMKUAcwG57kAByj4YwADYQ2HLiD4DJANwjjpnHvwC+tWqEixEKAIKKAjLiYlylZBAAekEIQxpMOPESsUqdBmGDQarLyDAD0obZgCAB0tNq0COKYLgDCnggAyupyFp5QNAIEIDIArghg+FAAFACUBQwMwDDIVWAAFsAY0UWl5ZXIALxDyGnMWcG5xFB1vg1+bSIA7sggEMsAKgCeghAAolAi1QJzDADkRgBGMohgjEkYLgBEk9CPjHAgIPi3FyigHB9-HBIIRkIRgFA8GBxJtoqdjg0avw5toGPEGMJgIpgSgAf4EMhuBAwC9qjIgjwamxRnhxjxSfUGk0WjJogCoGAMAB1YDtKqPOCKAAMpkeNRmCIYkLAJSgIBWa2QJlMNMy2W4pNqyIamls4iwjLm7SWCo22z2B0q-IAclRmHlkJQSk5Hf12ihuFiIPKZDwxdq0QJ0chwo7QKD3cgALbAhAdORgjxTZAfUH24gCQQlC7iYAEvF5xOWKrk9jqqmuLAvMjeQ3IaWy+XtTrRIkkpPQEucGrRdMQLvTbXBrM5wsFgl99b4AASYCj4gHFLkErmPVufZrNgGyGbXT7A6RCIbcp3HS6bc1Mh7FVn86qG+s+EPgYE+9LvuXbHQVY7m58CONfBllWM0dn2Q4qlOABZYk2iIZBHj7N4vluYAo0ESQo29EE4WfZBgxvOcF1ASgvzcatHwrD9uDrQDgMVLYwMtapoNg+DEI7Kdb3EZDvmQNCMIgLDwBIXChziHREmSJUzFVOkcg7fJ7EcZwRnSeSNUUxk1ygMoKmqFcGgwEodgM8TXw7Rcy2CCtlQo2tZjCCI+xTMwEWZKoAEJWXZTkeT5AVhVFcU63mE0QOQRiLQgx5yGxXNQUFUxrL9PCXzmUNCCoSMY09BAdDmY95UchpLFYBCkseAAaSUhBEMRJDYR4Y1AaraqUFQmoAVmiUUapOHcAigJqWpANqUXMvwZyI+9f0fNg7Lm7wqPVOsiuQAADWqAB5wUUAA+WqGG2toAGZ9oAEmoB9vG6dJNG20IzsOgbjpKcQXte47c32gAFeqJCkZArpuyhomEURAYe0IfqOhptp+gAZCBlFUYHrqWsGOvEaHYa+77gH29YhrYEHMfwaJ-GgXHCbhx73s+uZHr2xnNvE+JQwAVQwOAiVsOw4HQyRaE4TZtPwYp13JwY1LGdVSV7SzApFaIACZeq6qDeqFaIddMIUdaFABOXqADZdZNoV-UKCWMHwSRonEfBuFmyw-0PG3JeQNoiJluT5cUxXLC4mbldMNWNa1-Xde1w2TdMc3jd162GB6e2IEd52qh9+cPacsEIShZASh5okWE9jhXPMLTtwi5V-YmRStQr24kvsrcq4V-cw4j0xNe1mP9bjs2LeTvC04dp2Xbb8nD11BBYzaFpoEOQyJ4zqeqhXyo59oIA) using TypeScript definitions for the decoded info, an abstract decoder class with a factory for the actual decoders (based on the string prefix), and a `toHtml` method that takes the decoded info.

This would allow you to do:

```typescript
try {
  const decodedInfo = CodecStringDecoder.decode("av01.2.15M.10.0.100.09.16.09.0");
  console.log(decodedInfo);

  const html = CodecStringDecoder.decodeToHtml("av01.2.15M.10.0.100.09.16.09.0");
  console.log(html);

  // direct usage:
  const av1Decoder = new Av1CodecStringDecoder();
  const av1DecodedInfo = av1Decoder.decode("av01.2.15M.10.0.100.09.16.09.0");
  console.log(av1DecodedInfo);
} catch (error) {
  console.log(error);
}
```

Error handling will be done by means of exceptions.

That said, if errors should be allowed while still creating *some* output, an `error` property could be added to the return type.

**Comment by slhck** [comment]
PS: I'm willing to convert your existing code, of course, once we agree on how to proceed. If you believe that this would go way beyond what you initially intended, I could of course just create a new project! Just let me know what you think.

**Comment by paulhiggs** [comment]
I'm happy to expand the current code base to suit different use cases (without breaking the original ambition) so give me some time to update the codebase to provide generic, reformattable results and then you could repackage that for node.js etc.


________________________________

**Comment by asrashley** [comment]
I have created a fork of this project that keeps the current design of producing HTML output, but using ESM modules. This allowed me to use the code in a project where putting everything in the global JS namespace wasn't an option.

Annoyingly, it shows up as a lot of code changes (due to editor whitespace cleanup) but isn't actually that many changes. Hence why I didn't make it a pull request to the main repository.

https://github.com/asrashley/codec-string/pull/1

**Comment by paulhiggs** [comment]
Thanks @asrashley, I have merged your fork, and subsequently updated the enviroment to work with VScode, eslint and perttier.
